### ISSUE TITLE
Need to define the discovery types and vocabulary

### ISSUE THREAD

**Issue by farshidtz** [w3c/wot-discovery#54]
Some types and vocabulary used in Discovery spec and [Directory's TD](https://github.com/w3c/wot-discovery/blob/master/directory.td.json) are not part of the [TD context](https://github.com/w3c/wot-thing-description/blob/master/context/td-context-1.1.jsonld). 

We can extend the context locally (see [context-extensions](https://www.w3.org/TR/wot-thing-description/#sec-context-extensions)) or have them added to TD's main context.

To be included:
- [x] `combo` scheme in SecurityScheme (discussed in https://github.com/w3c/wot-thing-description/issues/901) - added to [TD 1.1](https://github.com/w3c/wot-discovery/issues/54)
- [x] `additionalResponses` in Form (discussed in https://github.com/w3c/wot-thing-description/issues/617) - added to [TD 1.1](https://github.com/w3c/wot-thing-description/pull/1042)
- [x] type for directory TDs (discussed in https://github.com/w3c/wot-discovery/issues/43) - added to [Discovery context](https://github.com/w3c/wot-discovery/blob/master/context/discovery-context.jsonld)
- [x] type for link TDs (see https://github.com/w3c/wot-discovery/issues/34#issuecomment-740009713) - added to [Discovery context](https://github.com/w3c/wot-discovery/blob/master/context/discovery-context.jsonld)
- [x] Registration annotations (see https://github.com/w3c/wot-discovery/issues/98#issuecomment-739245916) - added to [Discovery context](https://github.com/w3c/wot-discovery/blob/master/context/discovery-context.jsonld)

**Comment by mmccool** [comment]
Should create issue(s) in the wot-thing-description for these so the TD task force sees them.   Combination scheme is still under discussion; the two need issues.   Please link here.

**Comment by farshidtz** [comment]
alternateResponses is being discussed in https://github.com/w3c/wot-thing-description/issues/617

**Comment by relu91** [comment]
See my comment: https://github.com/w3c/wot-discovery/issues/43#issuecomment-762186016

**Comment by mmccool** [comment]
I think the last one (registration annotation) should probably be in its own context, since it only appears in directory responses when requested.  See also comment from @relu91

**Comment by mmccool** [comment]
Note also "combo" scheme has been closed.

**Comment by farshidtz** [comment]
We have now defined `discovery:DirectoryDescription` and `discovery:LinkDescription` types (see [discovery-context.jsonld](https://github.com/w3c/wot-discovery/blob/master/context/discovery-context.jsonld)). The Description prefix is to distinguish for e.g. between metadata of the Directory and the actual Directory. I don't know if this is really useful in practice. It may also get confusing as it is inconsistent with the use of Thing (not ThingDescription) in [`td:Thing`](https://github.com/w3c/wot-thing-description/blob/f445abae105cd694dc70cb6e77f34083a0d34101/context/td-context-1.1.jsonld#L243). We could change to `discovery:Directory` and `discovery:Link`.

**Comment by AndreaCimminoArriaga** [comment]
Following the comment of @farshidtz, and I think that also related to what @relu91 said before, I think we should develop an ontology for discovery that somehow extends the current ontology. Then, we can encapsulate our ontology in the context (similar to how @farshidtz  did in [discovery-context.jsonld](https://github.com/w3c/wot-discovery/blob/master/context/discovery-context.jsonld)). Notice that defining our ontology has many benefits, like avoiding name space collision, been independent from the current wot-td sub-group, and having more control on the properties we need (additionally they could be as many as we need, we will not find scalability problems). To this end, I already started drafting an ontology with the feedback of @farshidtz, maybe we could check the ontology next week? or I could paste it in this issue?

**Comment by AndreaCimminoArriaga** [comment]
In addition, another issue to consider is the terms required for pagination. I think in the last meeting it was suggested to mix JSON-LD framed and regular JSON for the pagination information. However, this has a potential problem. What if a user asks the same results in any other RDF serialisation different from JSON-LD framed? in that case the regular JSON information could not be embedded in the response, and thus, the pagination information will be lost. The only way to preserve such information is considering the terms required for it (next, count, etc.) in the ontology so they can be used in the JSON-LD and also in other serialisations of RDF.

**Comment by AndreaCimminoArriaga** [comment]
I have been doing some research on the pagination issue. The main problem of the pagination in the current solution is that the JSON-LD framed is mixing data (the TDs) with server information (the pages), which is very implementation dependent and is non related with the actual data. If the pagination information appears in the JSON-LD framed, it means we need to include these terms (e.g., nextLink) in the ontology, which is not correct from the ontology modelling perspective.

As a result, I think we could adopt [the solution](https://www.w3.org/TR/ldp-paging/) proposed by the W3C for the standard [LDP (Linked Data Platforms)](https://www.w3.org/TR/ldp/). In their solution, the basic idea is that the servers only publish RDF data, in our case an array of JSON-LD framed without the pagination info. If there is pagination, the server returns a code 303 with the next link. Additionally, there are several parameter to configure the pages and the sizes. I think @farshidtz commented a solution similar to this one, consider that following this approach would be as easy as adopting the [W3C Linked Data Platform Paging 1.0 document](https://www.w3.org/TR/ldp-paging/).

**Comment by farshidtz** [comment]
The new types and vocabulary have been defined. The details are available in the issue description.
